### ISSUE TITLE
HELP: How to construct goro sequential input from []float64

### ISSUE THREAD

**Issue by s4m-mo** [aunum/goro#6]
I am really struggling to turn a `[]float64` into a Goro Sequential compatible input because of the limited examples on the Goro and Gorgonia libraries. Would it be possible for a brief explanation on how to do this?

**Comment by pbarker** [comment]
Hey, its been awhile since I've worked on this, but take a look at https://github.com/aunum/goro/blob/master/pkg/v1/model/io.go#L156 and you would likely need to set the type to `float64` https://github.com/aunum/goro/blob/master/pkg/v1/model/io.go#L35

**Comment by s4m-mo** [comment]
Thanks

**Comment by s4m-mo** [comment]
Just another note, because of the lack of documentation I was wondering how you can specify whether to run the Goro Sequential network on the CPU or GPU
